feat: Allow customization of the installation namespace
keptn-contrib/prometheus-service pull request #328
Opened 2022-06-29 11:47 UTC by Raffy23

## This PR
- allows customization of the namespace in which Keptn and Prometheus are installed
- removes a lot of unnecessary permissions form the service user

2022-06-29 12:49 UTC, pchila commented on README.md
> +    ```bash
Maybe specify somewhere that the command will assume `keptn` and `monitoring` as default namespaces if not already set in a previous install...

2022-06-29 14:54 UTC, christian-kreuzberger-dtx requested changes
Left some comments

2022-06-29 14:54 UTC, christian-kreuzberger-dtx commented on utils/k8s.go
> +}
Would it be possible to just pass the current namespace via an enviornment variable instead?
```
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
```

2022-06-29 14:54 UTC, christian-kreuzberger-dtx commented on utils/prometheus/prometheus.go
> +const alertManagerYamlTemplate = `global:
I'd very much prefer to leave it as it is right now, there are different scenarios when this might change in the future.

2022-06-29 14:54 UTC, christian-kreuzberger-dtx commented on utils/prometheus/prometheus.go
> +func generateAlterManagerYaml(namespace string) string {
typo: Alter -> Alert

2022-07-01 06:50 UTC, christian-kreuzberger-dtx commented on utils/env.go
> +	K8sNamespace                  string `envconfig:"K8s_NAMESPACE" required:"true"`
typo in `K8s_NAMESPACE` - should be `K8S_NAMESPACE`

2022-07-01 06:51 UTC, christian-kreuzberger-dtx requested changes
left one more comment - also you have a conflict with README

2022-07-04 11:05 UTC, christian-kreuzberger-dtx approved these changes
LGTM

2022-07-04 11:23 UTC, merged